name: test

on:
  - push

jobs:
  create-matrix:
    name: create matrix
    runs-on: ubuntu-latest
    outputs:
      numbers: ${{ steps.number-list.outputs.value }}
    steps:
      - run: echo "::set-output name=value::[1,2,3,4,5]"
        id: number-list
  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - create-matrix
    strategy:
      fail-fast: false
      matrix:
        number: ${{ fromJSON(needs.create-matrix.outputs.numbers) }}
    steps:
      - run: echo "${{ matrix.number }}"
