name: test

on:
  - push

jobs:
  create-matrix:
    name: create matrix
    runs-on: ubuntu-latest
    output: ${{ steps.versions.outputs.value }}
    steps:
      - run: echo "::set-output name=value::[1,2,3,4,5]"
        id: versions
  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - create-matrix
    strategy:
      fail-fast: false
      matrix:
        number: ${{ fromJSON(needs.create-matrix.outputs.versions) }}
    steps:
      - run: echo "${{ matrix.number }}"
